test_duration: 300
user_prefix: 'longevity-scylla-operator-3h-multitenant'
n_db_nodes: 4
scylla_version: "5.0.2"
k8s_tenants_num: 2

# Stress options
prepare_write_cmd:  "fake__prepare_write_cmd__all_tenants__single_str"
prepare_verify_cmd: [
    "fake__prepare_verify_cmd__all_tenants__part1",
    "fake__prepare_verify_cmd__all_tenants__part2",
]
stress_cmd: [
    "fake__stress_cmd__all_tenants__part1",
    "fake__stress_cmd__all_tenants__part2"
]
stress_read_cmd: "fake__stress_read_cmd__all_tenants__single_str"
stress_cmd_w: "fake__stress_cmd_w__all_tenants__single_str"
stress_cmd_r: [[
    "fake__stress_cmd_r__tenant1__part1",
    "fake__stress_cmd_r__tenant1__part2"
], [
    "fake__stress_cmd_r__tenant2__single_str_in_list"
]]
stress_cmd_m: [[
    "fake__stress_cmd_m__tenant1__part1",
    "fake__stress_cmd_m__tenant1__part2"
],
    "fake__stress_cmd_m__tenant2__single_str"
]

# Non-stress options
nemesis_class_name: [
    "FakeNemesisClassNameForTenant1",
    "FakeNemesisClassNameForTenant2"
]
nemesis_selector: [[
    "fake__nemesis_selector__tenant1__part1",
    "fake__nemesis_selector__tenant1__part2"
], [
    "fake__nemesis_selector__tenant2"
]]
nemesis_interval: [5, 7]
nemesis_sequence_sleep_between_ops: [3, 5]
nemesis_during_prepare: [False, True]
nemesis_seed: ["024", "135"]
nemesis_add_node_cnt: [1, 2]
space_node_threshold: [1357, "2468"]
nemesis_filter_seeds: [False, True]
nemesis_exclude_disabled: [True, False]
nemesis_multiply_factor: [5, 6]
round_robin: [True, False]
