[tool.ruff]
<<<<<<< HEAD
lint.select = ["PL", "PLR0916", "PLR0913","PLR0914", "YTT", "BLE", "F841", "F401"]
||||||| parent of 2686304fd (feature(ruff): scan for mutable-argument-default (B006))
lint.select = [
    "BLE",
    "F401", "F821", "F823", "F841",
    "PL", "PLR0913","PLR0914", "PLR0916",
    "YTT",
    "F541",
    "PIE",
]
=======
lint.select = [
    "BLE",
    "F401", "F821", "F823", "F841",
    "PL", "PLR0913","PLR0914", "PLR0916",
    "YTT",
    "F541",
    "PIE",
    "B006",
]
>>>>>>> 2686304fd (feature(ruff): scan for mutable-argument-default (B006))

lint.ignore = ["E501", "PLR2004"]

target-version = "py310"

force-exclude = true
line-length = 240
respect-gitignore = true

lint.preview = true
lint.explicit-preview-rules = true

[tool.ruff.lint.pylint]
max-args = 12
max-statements = 100
max-branches = 24
max-locals = 15
