apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-kubernetes-ingress
  namespace: haproxy-controller
data:
  load-balance: "roundrobin"
  maxconn: "$HAPROXY_MAXCONN"
  src-ip-header: "True-Client-IP"
  http-keep-alive: "true"
