instance_provision: 'spot_low_price'
region_name:
  - eu-west-1
user_credentials_path: '~/.ssh/scylla-qa-ec2'
instance_type_loader: 'c4.xlarge'
instance_type_monitor: 't2.small'
regions_data:
  us-east-1:
    security_group_ids: 'sg-c5e1f7a0'
    subnet_id: 'subnet-ec4a72c4'
    ami_id_loader: 'ami-050c06c3e20036edc' # Loader dedicated AMI
    ami_id_monitor: 'ami-01d6b0d7e0d98969b' # Monitor dedicated AMI
  eu-west-1:
    security_group_ids: 'sg-059a7f66a947d4b5c'
    subnet_id: 'subnet-088fddaf520e4c7a8'
    ami_id_loader: 'ami-0006222380fb72d8d' # Loader dedicated AMI
    ami_id_monitor: 'ami-0f478f18d613e3662' # Monitor dedicated AMI

aws_root_disk_size_monitor: 20  # GB, remove this field if default disk size should be used
aws_root_disk_name_monitor: "/dev/sda1"  # use "/dev/xvda" for Debian 8 image
ami_db_scylla_user: 'centos'
ami_loader_user: 'centos'
ami_monitor_user: 'centos'
