instance_provision: 'spot'
spot_max_price: 0.60
instance_provision_fallback_on_demand: false
region_name:
  - eu-west-1
user_credentials_path: '~/.ssh/scylla-qa-ec2'
instance_type_loader: 'c5.xlarge'
instance_type_monitor: 't3.large'
# manual on creating loader AMI's: see docs/new_loader_ami.md
regions_data:
  us-east-1: # US East (N. Virginia)
    ami_id_loader: 'ami-0915f1c89aa5deed7' # scylla-qa-loader-ami-v20-ubuntu22
    ami_id_monitor: 'ami-0c7217cdde317cfec' # ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20231207
  us-west-2: # US West (Oregon)
    ami_id_loader: 'ami-021c384e804a5214a' # scylla-qa-loader-ami-v20-ubuntu22
    ami_id_monitor: 'ami-008fe2fc65df48dac' # ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20231207
  eu-west-1: # Europe (Ireland)
    ami_id_loader: 'ami-0f18f01a34f2b489c' # scylla-qa-loader-ami-v20-ubuntu22
    ami_id_monitor: 'ami-0905a3c97561e0b69' # ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20231207
  eu-west-2: # Europe (London)
    ami_id_loader: 'ami-06d13f74d77130f17' # scylla-qa-loader-ami-v20-ubuntu22
    ami_id_monitor: 'ami-0e5f882be1900e43b' # ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20231207
  eu-north-1: # Europe (Stockholm)
    ami_id_loader: 'ami-02fc787a21bb5f140' # scylla-qa-loader-ami-v20-ubuntu22
    ami_id_monitor: 'ami-0014ce3e52359afbd' # ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20231207
  eu-central-1: # Europe (Frankfurt)
    ami_id_loader: 'ami-0b269807b3c56bde0' # scylla-qa-loader-ami-v20-ubuntu22
    ami_id_monitor: 'ami-0faab6bdbac9486fb' # ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20231207

availability_zone: 'a'
root_disk_size_monitor: 50  # GB, remove this field if default disk size should be used
root_disk_size_db: 30  # GB, increase root disk for larger swap (maximum: 16G)
root_disk_size_loader: 30  # GB, Increase loader disk in order to have extra space for a larger swap
loader_swap_size: 10240  #10GB SWAP space
ami_db_scylla_user: 'scyllaadm'
ami_loader_user: 'ubuntu'
ami_monitor_user: 'ubuntu'
aws_instance_profile_name_db: 'qa-scylla-manager-backup-instance-profile'

ami_id_db_scylla: ''
ami_id_db_oracle: ''

use_preinstalled_scylla: true

backup_bucket_backend: 's3'
backup_bucket_location: 'manager-backup-tests-us-east-1'
backup_bucket_region: 'us-east-1'

data_volume_disk_num: 0
data_volume_disk_type: 'gp2'
data_volume_disk_size: 500
data_volume_disk_iops: 10000 # depend on type iops could be 100-16000 for io2|io3 and 3000-16000 for gp3
