instance_provision: 'spot_low_price'
region_name:
  - eu-west-1
user_credentials_path: '~/.ssh/scylla-qa-ec2'
instance_type_loader: 'c5.xlarge'
instance_type_monitor: 't3.small'
regions_data:
  us-east-1:
    security_group_ids: 'sg-c5e1f7a0'
    subnet_id: 'subnet-ec4a72c4'
    ami_id_loader: 'ami-0803fc42f8277925f' # Loader dedicated AMI
    ami_id_monitor: 'ami-02eac2c0129f6376b' # Official CentOS Linux 7 x86_64 HVM EBS ENA 1901_01
  eu-west-1:
    security_group_ids: 'sg-059a7f66a947d4b5c'
    subnet_id: 'subnet-088fddaf520e4c7a8'
    ami_id_loader: 'ami-0668349068972415c' # Loader dedicated AMI
    ami_id_monitor: 'ami-0ff760d16d9497662' # Official CentOS Linux 7 x86_64 HVM EBS ENA 1901_01

aws_root_disk_size_monitor: 20  # GB, remove this field if default disk size should be used
aws_root_disk_name_monitor: "/dev/sda1"  # use "/dev/xvda" for Debian 8 image
ami_db_scylla_user: 'centos'
ami_loader_user: 'centos'
ami_monitor_user: 'centos'
