instance_provision: 'spot_low_price'
region_name:
  - us-east-1
user_credentials_path: '~/.ssh/scylla-qa-ec2'
instance_type_loader: 'c4.xlarge'
instance_type_monitor: 't2.small'
regions_data:
  us-east-1:
    security_group_ids: 'sg-c5e1f7a0'
    subnet_id: 'subnet-ec4a72c4'
    ami_id_loader: 'ami-0ca8dbf790f055795' # Scylla 2.3.2
    ami_id_monitor: 'ami-9887c6e7' # Clean CentOs 7 ami
  us-west-2:
    security_group_ids: 'sg-81703ae4'
    subnet_id: 'subnet-5207ee37'
    ami_id_loader: 'ami-0ca8dbf790f055795' # Scylla 2.3.2
    ami_id_monitor: 'ami-9887c6e7' # Clean CentOs 7 ami

aws_root_disk_size_monitor: 10  # GB, remove this field if default disk size should be used
aws_root_disk_name_monitor: "/dev/sda1"  # use "/dev/xvda" for Debian 8 image
ami_db_scylla_user: 'centos'
ami_loader_user: 'centos'
ami_monitor_user: 'centos'