gce_datacenter: 'us-east1-b'
gce_network: 'qa-vpc'
gce_image: 'https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-7'
gce_image_username: 'scylla-test'

gce_instance_type_loader: 'n1-standard-1'
gce_root_disk_type_loader: 'pd-standard'
gce_n_local_ssd_disk_loader: 0

gce_instance_type_monitor: 'n1-standard-2'
gce_root_disk_type_monitor: 'pd-standard'
gce_root_disk_size_monitor: 50
gce_n_local_ssd_disk_monitor: 0

gce_instance_type_db: 'n1-standard-2'
gce_root_disk_type_db: 'pd-ssd'
gce_root_disk_size_db: 50
gce_n_local_ssd_disk_db: 3
