instance_provision: 'spot'
gce_datacenter: 'us-east1'
gce_network: 'qa-vpc'

gce_image_db: 'https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-7'
gce_image_loader: 'https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-7'
gce_image_monitor: 'https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-7'
gce_image_username: 'scylla-test'

gce_instance_type_loader: 'e2-standard-2'
gce_root_disk_type_loader: 'pd-standard'
gce_n_local_ssd_disk_loader: 0

gce_instance_type_monitor: 'e2-medium'
gce_root_disk_type_monitor: 'pd-standard'
gce_root_disk_size_monitor: 50
gce_n_local_ssd_disk_monitor: 0

gce_instance_type_db: 'n1-highmem-8'
gce_root_disk_type_db: 'pd-ssd'
gce_root_disk_size_db: 50
gce_n_local_ssd_disk_db: 3

user_credentials_path: '~/.ssh/scylla-test'
