# Version of the kind to be used
mini_k8s_version: '0.14.0'

n_db_nodes: 4
k8s_n_scylla_pods_per_cluster: 3

scylla_version: '4.6.3'
scylla_mgmt_agent_version: '3.0.0'
mgmt_docker_image: 'scylladb/scylla-manager:3.0.0'

# NOTE: If 'k8s_scylla_operator_docker_image' not set then the one from helm chart will be used.
# To test nightly builds define it like this: 'scylladb/scylla-operator:nightly'
k8s_scylla_operator_docker_image: ''
k8s_scylla_operator_helm_repo: 'https://storage.googleapis.com/scylla-operator-charts/stable'
k8s_scylla_operator_chart_version: 'v1.7.2'
k8s_cert_manager_version: '1.8.0'

k8s_scylla_datacenter: 'dc-1'
k8s_scylla_rack: 'kind'
k8s_scylla_cluster_name: 'sct-cluster'
k8s_scylla_disk_gi: 5
k8s_scylla_disk_class: 'local-raid-disks'
k8s_minio_storage_size: '20Gi'

# NOTE: if we do not specify 'k8s_n_loader_pods_per_cluster' then value of the 'n_loaders' is used
n_loaders: 1
n_monitor_nodes: 1

user_credentials_path: '~/.ssh/scylla-test'
use_preinstalled_scylla: true
backtrace_decoding: false

# TODO: add '--abort-on-seastar-bad-alloc' arg to the 'append_scylla_args' option when
#       following operator bug gets fixed: https://github.com/scylladb/scylla-operator/issues/991
#       '--blocked-reactor-notify-ms 100' cannot be set, because it gets set by operator itself
append_scylla_args: '--abort-on-lsa-bad-alloc 1 --abort-on-internal-error 1 --abort-on-ebadf 1 --enable-sstable-key-validation 1'
docker_image: ''
backup_bucket_location: 'minio-bucket'
