libvirt_uri: 'qemu:///system'
libvirt_bridge: 'virbr0'
libvirt_loader_image: '/home/fruch/Projects/scylla-cluster-tests/CentOS-7-x86_64-GenericCloud.qcow2'
libvirt_loader_image_user: 'centos'
libvirt_loader_image_password: '123456'
libvirt_loader_os_type: 'linux'
libvirt_loader_os_variant: 'centos7.0'
libvirt_loader_memory: 2048
libvirt_db_image: '/home/fruch/Projects/scylla-cluster-tests/CentOS-7-x86_64-GenericCloud.qcow2'
libvirt_db_image_user: 'centos'
libvirt_db_image_password: '123456'
libvirt_db_os_type: 'linux'
libvirt_db_os_variant: 'centos7.0'
libvirt_db_memory: 2048
libvirt_monitor_image: '/home/fruch/Projects/scylla-cluster-tests/CentOS-7-x86_64-GenericCloud.qcow2'
libvirt_monitor_image_user: 'centos'
libvirt_monitor_image_password: '123456'
libvirt_monitor_os_type: 'linux'
libvirt_monitor_os_variant: 'centos7.0'
libvirt_monitor_memory: 2048
