openstack_auth_version: '3.x_password'
openstack_auth_url: 'http://1.2.3.4:5000'
openstack_user: 'put_your_user_here'
openstack_password: 'put_your_pass_here'
openstack_tenant: 'put_your_tenant_here'
openstack_service_type: 'compute'
openstack_service_name: 'nova'
openstack_service_region: 'put_your_region_here'
openstack_network: 'put_your_network_here'
# Openstack image: CentOS7
openstack_image: '56450641-b01e-4357-b7a9-8b02d6286d90'
openstack_image_username: 'centos'
openstack_instance_type_db: 'm1.small'
openstack_instance_type_loader: 'm1.small'
openstack_instance_type_monitor: 'm1.small'
