apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${K8S_LOADER_CLUSTER_NAME}
  namespace: ${K8S_NAMESPACE}
spec:
  selector:
    matchLabels:
      loader-cluster-name: ${K8S_LOADER_CLUSTER_NAME}
  serviceName: ${K8S_LOADER_CLUSTER_NAME}
  replicas: ${N_LOADERS}
  template:
    metadata:
      labels:
        loader-cluster-name: ${K8S_LOADER_CLUSTER_NAME}
    spec:
      # NOTE: 'affinity' will be updated in the code.
      affinity: {}
      containers:
        - name: loader
          image: ${DOCKER_IMAGE_WITH_TAG}
          tty: true
          command:
            - "/bin/bash"
            - "-c"
            - "--"
          # NOTE: the 'fake' env var usage is a workaround for 'envsubst' to keep env vars for runtime.
          #       Remove the workaround if the 'envsubst' stops getting applied to this template.
          args:
            - |
              cp /etc/scylla/cassandra/logback-tools.xml .
              # NOTE: following is needed by the YCSB tool to be able to work with secured port of alternator.
              if [ -d /YCSB ]; then
                if [ -f /tmp/alternator-ca.crt ]; then
                  if [ ! -f /tmp/alternator-ca.pem ]; then
                      openssl x509 -in /tmp/alternator-ca.crt -out /tmp/alternator-ca.pem
                  fi
                  if ! $${fake}JAVA_HOME/bin/keytool -list -v \
                          -keystore $${fake}JAVA_HOME/jre/lib/security/cacerts \
                          -storepass changeit | grep -q "Alias name: alternator-ca";
                  then
                    $${fake}JAVA_HOME/bin/keytool -importcert -v -trustcacerts -alias alternator-ca \
                        -file "/tmp/alternator-ca.pem" \
                        -keystore $${fake}JAVA_HOME/jre/lib/security/cacerts \
                        -storepass changeit -noprompt
                  fi
                fi
              fi
              cat
          resources:
            limits:
              cpu: ${POD_CPU_LIMIT}
              memory: ${POD_MEMORY_LIMIT}
            requests:
              cpu: ${POD_CPU_LIMIT}
              memory: ${POD_MEMORY_LIMIT}
      hostNetwork: false
