apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${K8S_LOADER_CLUSTER_NAME}
  namespace: ${K8S_NAMESPACE}
spec:
  selector:
    matchLabels:
      loader-cluster-name: ${K8S_LOADER_CLUSTER_NAME}
  serviceName: ${K8S_LOADER_CLUSTER_NAME}
  replicas: ${N_LOADERS}
  template:
    metadata:
      labels:
        loader-cluster-name: ${K8S_LOADER_CLUSTER_NAME}
    spec:
      # NOTE: 'affinity' will be updated in the code.
      affinity: {}
      containers:
        - name: loader
          image: ${DOCKER_IMAGE_WITH_TAG}
          tty: true
          command:
            - /bin/bash
            - -c
            - "cp /etc/scylla/cassandra/logback-tools.xml . ; cat"
          resources:
            limits:
              cpu: ${POD_CPU_LIMIT}
              memory: ${POD_MEMORY_LIMIT}
            requests:
              cpu: ${POD_CPU_LIMIT}
              memory: ${POD_MEMORY_LIMIT}
          # TODO: those mounts/securityContext should be remove once we'll stop using bare docker for loaders
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /usr/bin/docker
              name: docker-binary
            - mountPath: /var/run/docker.sock
              name: docker-socket
      volumes:
        - name: docker-binary
          hostPath:
            path: /usr/bin/docker
            type: File
        - name: docker-socket
          hostPath:
            type: Socket
      hostNetwork: false
