apiVersion: v1
kind: Pod
metadata:
  name: ${POD_NAME}
  namespace: default
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:

      # EKS
      - weight: 100
        preference:
          matchExpressions:
          - key: eks.amazonaws.com/nodegroup
            operator: In
            values:
            - auxiliary-pool
            - default-pool
      - weight: 50
        preference:
          matchExpressions:
          - key: eks.amazonaws.com/nodegroup
            operator: In
            values:
            - loader-pool
            - monitoring-pool

      # GKE
      - weight: 100
        preference:
          matchExpressions:
          - key: cloud.google.com/gke-nodepool
            operator: In
            values:
            - auxiliary-pool
            - default-pool
      - weight: 50
        preference:
          matchExpressions:
          - key: cloud.google.com/gke-nodepool
            operator: In
            values:
            - loader-pool
            - monitoring-pool

  containers:
  - name: ${POD_NAME}
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command:
      - /bin/sh
      - -c
      - while true; do sleep 900 ; done
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi
  restartPolicy: Always
