name: 'Auto Assign'
on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]
jobs:
  assignAuthor:
    name: Assign author to PR/issue
    runs-on: ubuntu-latest
    steps:
      - name: Assign author to PR/issue
        uses: technote-space/assign-author@v1
