name: Cache issues status
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  collect_n_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/dump_issues.py
          sparse-checkout-cone-mode: false
      - run: |
          mkdir -p issues
          for repo in scylladb scylla-enterprise scylla-manager scylla-operator scylla-cluster-tests scylla-dtest qa-tasks scylla-tools-java ; do
            .github/dump_issues.py --repository scylladb/$repo
          done
        env:
          GH_TOKEN: ${{ secrets.ISSUE_ASSIGNMENT_TO_PROJECT_TOKEN }}
      - name: Upload folder to bucket
        uses: a-sync/s3-uploader@2.0.1
        with:
          args: --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          S3_KEY: 'issues'
          FILE: ./issues
